import type { Category, Product } from "@/types";

export const MOCK_CATEGORIES: Category[] = [
  {
    id: "cat-1",
    name: "Notebooks",
    slug: "notebooks",
    subtitle: "Portátiles de alto rendimiento",
    image_url: "https://images.unsplash.com/photo-1496181133206-80ce9b88a853?w=800",
    created_at: new Date().toISOString(),
  },
  {
    id: "cat-2",
    name: "Smartphones",
    slug: "smartphones",
    subtitle: "Conectividad sin límites",
    image_url: "https://images.unsplash.com/photo-1511707171634-5f897ff02aa9?w=800",
    created_at: new Date().toISOString(),
  },
  {
    id: "cat-3",
    name: "Hardware",
    slug: "hardware",
    subtitle: "Componentes y periféricos",
    image_url: "https://images.unsplash.com/photo-1518770660439-4636190af475?w=800",
    created_at: new Date().toISOString(),
  },
  {
    id: "cat-4",
    name: "Accesorios",
    slug: "accesorios",
    subtitle: "Complementos esenciales",
    image_url: "https://images.unsplash.com/photo-1491553895911-0055eca6402d?w=800",
    created_at: new Date().toISOString(),
  },
];

export const MOCK_PRODUCTS: Product[] = [
  {
    id: "prod-1",
    name: 'MacBook Pro M3 Pro 14"',
    slug: "macbook-pro-m3-pro-14",
    description:
      "El portátil profesional de Apple con chip M3 Pro de 11 núcleos para flujos de trabajo exigentes.",
    price: 2499000,
    old_price: 2799000,
    image_url:
      "https://images.unsplash.com/photo-1517336714731-489689fd1ca8?w=800",
    images: [
      "https://images.unsplash.com/photo-1611186871525-63c7a4d7b92a?w=800",
    ],
    badge: "imported",
    rating: 4.9,
    reviews_count: 127,
    category_id: "cat-1",
    specs: {
      procesador: "Apple M3 Pro 11 núcleos",
      ram: "18 GB unificada",
      almacenamiento: "512 GB SSD",
      pantalla: '14.2" Liquid Retina XDR',
      batería: "Hasta 18 horas",
      peso: "1.61 kg",
    },
    is_featured: true,
    created_at: new Date().toISOString(),
    categories: { id: "cat-1", name: "Notebooks", slug: "notebooks" },
  },
  {
    id: "prod-2",
    name: "Dell XPS 15 9530",
    slug: "dell-xps-15-9530",
    description:
      'Pantalla OLED de 15.6" con Intel Core i9 y RTX 4070 para creadores de contenido exigentes.',
    price: 1899000,
    old_price: null,
    image_url:
      "https://images.unsplash.com/photo-1593642632559-0c6d3fc62b89?w=800",
    images: [],
    badge: "new",
    rating: 4.7,
    reviews_count: 84,
    category_id: "cat-1",
    specs: {
      procesador: "Intel Core i9-13900H",
      ram: "32 GB DDR5",
      almacenamiento: "1 TB SSD NVMe",
      pantalla: '15.6" OLED 3.5K',
      gpu: "NVIDIA RTX 4070 8GB",
      peso: "1.86 kg",
    },
    is_featured: true,
    created_at: new Date().toISOString(),
    categories: { id: "cat-1", name: "Notebooks", slug: "notebooks" },
  },
  {
    id: "prod-3",
    name: "iPhone 15 Pro Max 256GB",
    slug: "iphone-15-pro-max-256gb",
    description:
      "Titanio. Cámara pro de 48 MP. Chip A17 Pro. El smartphone más avanzado de Apple.",
    price: 1349000,
    old_price: 1499000,
    image_url:
      "https://images.unsplash.com/photo-1695048133142-1a20484d2569?w=800",
    images: [],
    badge: "sale",
    rating: 4.9,
    reviews_count: 312,
    category_id: "cat-2",
    specs: {
      procesador: "Apple A17 Pro",
      pantalla: '6.7" Super Retina XDR OLED',
      cámara: "48MP + 12MP + 12MP",
      batería: "4422 mAh",
      almacenamiento: "256 GB",
      "5G": "Sí",
    },
    is_featured: true,
    created_at: new Date().toISOString(),
    categories: { id: "cat-2", name: "Smartphones", slug: "smartphones" },
  },
  {
    id: "prod-4",
    name: "Samsung Galaxy S24 Ultra",
    slug: "samsung-galaxy-s24-ultra",
    description:
      'Pantalla Dynamic AMOLED 2X de 6.8" con S Pen integrado y cámara de 200 MP.',
    price: 1199000,
    old_price: null,
    image_url:
      "https://images.unsplash.com/photo-1610945265064-0e34e5519bbf?w=800",
    images: [],
    badge: "imported",
    rating: 4.8,
    reviews_count: 198,
    category_id: "cat-2",
    specs: {
      procesador: "Snapdragon 8 Gen 3",
      pantalla: '6.8" Dynamic AMOLED 2X',
      cámara: "200MP + 12MP + 50MP + 10MP",
      batería: "5000 mAh",
      almacenamiento: "256 GB",
      s_pen: "Integrado",
    },
    is_featured: true,
    created_at: new Date().toISOString(),
    categories: { id: "cat-2", name: "Smartphones", slug: "smartphones" },
  },
  {
    id: "prod-5",
    name: "NVIDIA RTX 4080 Super 16GB",
    slug: "nvidia-rtx-4080-super-16gb",
    description:
      "GPU de referencia para gaming 4K y renderizado profesional con arquitectura Ada Lovelace.",
    price: 899000,
    old_price: 999000,
    image_url:
      "https://images.unsplash.com/photo-1587202372634-32705e3bf49c?w=800",
    images: [],
    badge: "limited",
    rating: 4.9,
    reviews_count: 56,
    category_id: "cat-3",
    specs: {
      arquitectura: "Ada Lovelace",
      vram: "16 GB GDDR6X",
      tdp: "320W",
      puertos: "3x DP 1.4a + HDMI 2.1",
      pcie: "PCIe 4.0 x16",
    },
    is_featured: true,
    created_at: new Date().toISOString(),
    categories: { id: "cat-3", name: "Hardware", slug: "hardware" },
  },
  {
    id: "prod-6",
    name: "Logitech MX Master 3S",
    slug: "logitech-mx-master-3s",
    description:
      "El mouse de productividad definitivo con scroll electromagnético y sensor de 8000 DPI.",
    price: 89000,
    old_price: null,
    image_url:
      "https://images.unsplash.com/photo-1527864550417-7fd91fc51a46?w=800",
    images: [],
    badge: "new",
    rating: 4.8,
    reviews_count: 445,
    category_id: "cat-4",
    specs: {
      sensor: "Darkfield 8000 DPI",
      conexión: "USB-C / Bluetooth / Unifying",
      batería: "70 días",
      compatibilidad: "Windows / macOS / Linux",
      peso: "141g",
    },
    is_featured: false,
    created_at: new Date().toISOString(),
    categories: { id: "cat-4", name: "Accesorios", slug: "accesorios" },
  },
];
